/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.partial;

import dal.Database;
import dal.DerbyDatabase;
import entity.CurrentUser;
import entity.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author sagar
 */
public class FacultyProfile extends javax.swing.JPanel {

    
    private Database db;
    
    private String username;
    
    public FacultyProfile() {
        initComponents();
    
        db = new DerbyDatabase();
        setUserDetails();
    
    }

    
    private void setUserDetails(){
        User user = CurrentUser.getCurrentUser().getUser();
        username = user.getUsername();
        
        String[] userDetail = db.getUserDetails( user.getUsername() );
        
        nameField.setText (userDetail[1]);
        idField.setText (userDetail[2]);
        phoneField.setText (userDetail[3]);
        
        helloLabel.setText("Hello, " + username + " ("+ user.getType()+")");
        
        setAllSubject();
        setSelectedSubject ();
        
    }
    
    
    private void setAllSubject(){
        
        ArrayList <String> subject = db.getAllSubjects();
        allSubjectComboBox.removeAll();
        
        for (String s :subject){
            allSubjectComboBox.addItem(s);
        }
    }
    
    private void setSelectedSubject(){
        subjectComboBox.removeAllItems();
        ArrayList <String> subject = db.getSubjectByFacultyName (username);
        subjectComboBox.removeAll();
        
        for (String s :subject){
            subjectComboBox.addItem(s);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        helloLabel = new javax.swing.JLabel();
        removeSubjectButton = new javax.swing.JButton();
        subjectComboBox = new javax.swing.JComboBox<>();
        addSubjectButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        allSubjectComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 137, 212));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 76, 124, 32));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Faculty ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 126, 124, 32));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Phone no.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 124, 32));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 72, 420, 32));
        add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 176, 420, 32));
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 126, 420, 32));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(11, 95, 1));
        jLabel9.setText("Add or Remove Subject that you want/don't want to teach");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 420, 20));

        updateButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(33, 137, 212));
        updateButton.setText("Update Details");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 150, 40));

        helloLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(254, 254, 254));
        helloLabel.setText("Hello");
        add(helloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 280, 32));

        removeSubjectButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        removeSubjectButton.setForeground(new java.awt.Color(212, 64, 33));
        removeSubjectButton.setText("remove subject");
        removeSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSubjectButtonActionPerformed(evt);
            }
        });
        add(removeSubjectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 150, 40));

        subjectComboBox.setBackground(java.awt.Color.white);
        subjectComboBox.setForeground(java.awt.Color.white);
        add(subjectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 270, 40));

        addSubjectButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addSubjectButton.setForeground(new java.awt.Color(33, 137, 212));
        addSubjectButton.setText("+add subject");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });
        add(addSubjectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 150, 40));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Selected Subjects");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 170, 32));

        allSubjectComboBox.setBackground(java.awt.Color.white);
        allSubjectComboBox.setForeground(java.awt.Color.white);
        add(allSubjectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 270, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("All Subjects");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 124, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to update your Details") == JOptionPane.OK_OPTION ){

            String name = nameField.getText();
            String id = idField.getText();
            String phone = phoneField.getText();

            boolean status;
            
            status = db.updateUserDetail (username , name , id, phone);
            
            if (status == true)
                JOptionPane.showMessageDialog(this, "Updated");
            else
                JOptionPane.showMessageDialog (this, "Sorry");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        
        String subject = allSubjectComboBox.getSelectedItem().toString();
        
        db.addFacultySubject (username, subject);
        
        setSelectedSubject();
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void removeSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSubjectButtonActionPerformed
        
        String subject = subjectComboBox.getSelectedItem().toString();
        
        db.removeFacultySubject (username, subject);
        
        setSelectedSubject();
    }//GEN-LAST:event_removeSubjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JComboBox<String> allSubjectComboBox;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton removeSubjectButton;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
