/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.partial;

import factory.View;
import factory.ViewFactory;
import java.awt.Color;
import javax.swing.JPanel;
import virtaulclassroom.IChangeView;

/**
 *
 * @author sagar
 */
public class HomeMenuItem extends javax.swing.JPanel {

    private IChangeView parent;
    private View view;
    
    
    public HomeMenuItem() {
        initComponents();
    }
    
    public HomeMenuItem(IChangeView parent, View view){
        this();
        this.parent = parent;
        this.view = view;
        this.setItem();
    }
    
    private void setItem(){
        
        itemNameLabel.setText(view.toString());
        
        if (view == View.Resources)
            itemIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/download_52px.png"))); 
        
        else if (view == View.Setting)
            itemIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/settings_48px.png"))); 
       
        else if (view == View.Assignment)
            itemIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/list_64px.png"))); 
       
        else if (view == View.LiveSessionRoom)
                itemIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/classroom_48px.png"))); 

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        itemNameLabel = new javax.swing.JLabel();
        itemIconLabel = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.controlHighlight);
        setPreferredSize(new java.awt.Dimension(130, 95));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 22, -1, -1));

        itemNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        itemNameLabel.setForeground(new java.awt.Color(45, 118, 232));
        itemNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNameLabel.setText("item name");
        itemNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(itemNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 30));

        itemIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/home_48px.png"))); // NOI18N
        add(itemIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setItemBackground (this);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        resetItemBackground (this);
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        parent.requestView( ViewFactory.getView(parent, view));
    }//GEN-LAST:event_formMouseClicked

    
    
    private void setItemBackground (JPanel panel){
        panel.setBackground (Color.WHITE);
    }

    private void resetItemBackground (JPanel panel){
        panel.setBackground (java.awt.SystemColor.controlHighlight);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemIconLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
