/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


/**
 *
 * @author sagar
 */
public class LectureRoom extends javax.swing.JPanel {

    /**
     * Creates new form ClassRoom
     */
    
    
    public LectureRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        subjectName1 = new javax.swing.JLabel();
        playVideoPanel = new javax.swing.JPanel();
        subjectName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(45, 118, 232));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(222, 106, 106));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 6, 86));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Subjects");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 70));

        jLabel2.setBackground(new java.awt.Color(64, 40, 207));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Lecture 2: Database Vs FileSystem");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 40));

        jLabel3.setBackground(new java.awt.Color(102, 83, 230));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Lecture 1 : Introduction to DBMS");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 40));

        jLabel5.setBackground(new java.awt.Color(64, 40, 207));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Lecture 5: Data Models ");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 260, 40));

        jLabel6.setBackground(new java.awt.Color(64, 40, 207));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Lecture 3: Types of Database");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 40));

        jLabel7.setBackground(new java.awt.Color(64, 40, 207));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Lecture 4: Artitacture of DBMS");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 40));

        jLabel8.setBackground(new java.awt.Color(64, 40, 207));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("see more...");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, 40));

        jLabel10.setBackground(new java.awt.Color(64, 40, 207));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Lecture 6: Relation, Keys and Attributes");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, 40));

        subjectName1.setBackground(new java.awt.Color(46, 30, 144));
        subjectName1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        subjectName1.setForeground(java.awt.Color.white);
        subjectName1.setText("Database Management System");
        subjectName1.setAlignmentX(0.5F);
        subjectName1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        subjectName1.setOpaque(true);
        jPanel2.add(subjectName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 60));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        playVideoPanel.setBackground(new java.awt.Color(5, 0, 0));

        subjectName.setBackground(new java.awt.Color(46, 30, 144));
        subjectName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        subjectName.setForeground(java.awt.Color.white);
        subjectName.setText("Under Construction");
        subjectName.setAlignmentX(0.5F);
        subjectName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        subjectName.setOpaque(true);

        javax.swing.GroupLayout playVideoPanelLayout = new javax.swing.GroupLayout(playVideoPanel);
        playVideoPanel.setLayout(playVideoPanelLayout);
        playVideoPanelLayout.setHorizontalGroup(
            playVideoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playVideoPanelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(subjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        playVideoPanelLayout.setVerticalGroup(
            playVideoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playVideoPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(subjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        add(playVideoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 620, 410));

        jPanel4.setBackground(new java.awt.Color(134, 139, 219));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, 410));
    }// </editor-fold>//GEN-END:initComponents

    
    public void playLecure (){
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel playVideoPanel;
    private javax.swing.JLabel subjectName;
    private javax.swing.JLabel subjectName1;
    // End of variables declaration//GEN-END:variables
}
