/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dal.Database;
import dal.DerbyDatabase;
import factory.View;
import factory.ViewFactory;
import virtaulclassroom.IChangeView;

/**
 *
 * @author Mukesh-PC
 */
public class Login extends javax.swing.JPanel {

    IChangeView parent;
    Database db;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        db = new DerbyDatabase();
    }

    public Login(IChangeView frame){
        this();
        parent = frame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LoginBody = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        signupLabel = new javax.swing.JLabel();
        invalidUserLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 137, 212));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginHeader.setBackground(new java.awt.Color(33, 137, 212));
        LoginHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Login");
        LoginHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 130, 50));

        add(LoginHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 107));

        LoginBody.setBackground(new java.awt.Color(33, 137, 212));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Password");

        usernameField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        usernameField.setInputVerifier(new validation.UsernameVerifier());

        passwordField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        loginButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(33, 137, 212));
        loginButton.setText("login");
        loginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jCheckBox1.setForeground(java.awt.Color.white);
        jCheckBox1.setText("Remember Me");

        signupLabel.setBackground(java.awt.Color.white);
        signupLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        signupLabel.setForeground(java.awt.Color.white);
        signupLabel.setText("Don't have an Account? Sign up");
        signupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabelMouseClicked(evt);
            }
        });

        invalidUserLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        invalidUserLabel.setForeground(new java.awt.Color(164, 45, 40));
        invalidUserLabel.setText("warning label, warnings will appear here");

        javax.swing.GroupLayout LoginBodyLayout = new javax.swing.GroupLayout(LoginBody);
        LoginBody.setLayout(LoginBodyLayout);
        LoginBodyLayout.setHorizontalGroup(
            LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBodyLayout.createSequentialGroup()
                .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(invalidUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginBodyLayout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LoginBodyLayout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jCheckBox1))
                                .addGroup(LoginBodyLayout.createSequentialGroup()
                                    .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(48, 48, 48)
                                    .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                        .addComponent(passwordField)))))
                        .addGroup(LoginBodyLayout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(signupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        LoginBodyLayout.setVerticalGroup(
            LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invalidUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(LoginBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jCheckBox1)
                .addGap(15, 15, 15)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(signupLabel)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        add(LoginBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 133, 520, 400));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons/group.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Virtual Classroom");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 170, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void signupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseClicked
        
        parent.requestView(ViewFactory.getView(parent, View.Register));
        
    }//GEN-LAST:event_signupLabelMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String username = usernameField.getText();
        String password = String.valueOf(passwordField.getPassword());
        boolean exist = db.userExist(username);
        System.out.println(exist?"worked":"nevermind");
        if (db.authenticUser(username , password))
            parent.requestView(ViewFactory.getView(parent, View.Home));
        
        else
            invalidUserLabel.setText ("Please Enter correct Details");
        
    }//GEN-LAST:event_loginButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginBody;
    private javax.swing.JPanel LoginHeader;
    private javax.swing.JLabel invalidUserLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
